
name: build-toolchain

on:
  #schedule:
  #  - cron: '10 0 * * MON'
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      ARCHS: ${{ matrix.arch }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        os:
          - "macos-13"
          - "macos-14"
        include:
          - os: "macos-13"
            arch: "x86_64"
          - os: "macos-14"
            arch: "arm64"
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Loading toolchain-${{ matrix.arch }} cache
      uses: actions/cache@main
      with:
        path: ${{ github.workspace }}/workspace
        key: toolchain-${{ matrix.arch }}
        restore-keys: toolchain-
    - name: Switch to Xcode 15.2
      run: |
        sudo xcode-select --reset
        sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer   
    - name: Remove stray upstream python binary symlinks under /usr/local
      run: |
        find /usr/local/bin -lname '*/Library/Frameworks/Python.framework/*' -delete -print
        brew unlink python
    - name: Build toolchain 
      run: |
        chmod +x ./build-toolchain.sh
        ./build-toolchain.sh
    - name: Get current timestamp
      run: echo "date=$(date +%Y-%m-%d)" >> $GITHUB_ENV 
    - name: Zip toolchain-${{ matrix.arch }} 
      continue-on-error: true
      run: |
        zip -r -y toolchain-${{ matrix.arch }}-${{ env.date }}.zip workspace/*
        cp toolchain-${{ matrix.arch }}-${{ env.date }}.zip toolchain-${{ matrix.arch }}-latest.zip
    - name: Delete
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: toolchain
        assets: toolchain-${{ matrix.arch }}-latest.zip
        fail-if-no-assets: false
        fail-if-no-release: false
    - name: Upload toolchain
      continue-on-error: true
      uses: softprops/action-gh-release@master
      with:
        tag_name: toolchain
        name: toolchain
        files: toolchain*.zip

