
name: build-tools

on:
  #schedule:
  #  - cron: '10 0 * * MON'
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      ARCHS: ${{ matrix.arch }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        os:
          - "macos-13"
          - "macos-15"
        include:
          - os: "macos-13"
            arch: "x86_64"
            xcode: "Xcode_15.2"
          - os: "macos-15"
            arch: "arm64"
            xcode: "Xcode_16.4"
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Loading tools-${{ matrix.arch }} cache
      uses: actions/cache@main
      with:
        path: ${{ github.workspace }}/tools
        key: tools-${{ matrix.arch }}
        restore-keys: tools-
    - name: Switch to Xcode
      run: |
        sudo xcode-select --reset
        sudo xcode-select -s /Applications/${{ matrix.xcode }}.app/Contents/Developer
    - name: Remove stray upstream python binary symlinks under /usr/local
      run: |
        find /usr/local/bin -lname '*/Library/Frameworks/Python.framework/*' -delete -print
        brew unlink python
    - name: Build tools 
      run: |
        chmod +x ./build-tools.sh
        ./build-tools.sh
    - name: Get current timestamp
      run: echo "date=$(date +%Y-%m-%d)" >> $GITHUB_ENV 
    - name: Zip tools-${{ matrix.arch }} 
      continue-on-error: true
      run: |
        zip -r -y tools-${{ matrix.arch }}-${{ env.date }}.zip tools/*
        cp tools-${{ matrix.arch }}-${{ env.date }}.zip tools-${{ matrix.arch }}-latest.zip
    - name: Delete
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: tools
        assets: tools-${{ matrix.arch }}-latest.zip
        fail-if-no-assets: false
        fail-if-no-release: false
    - name: Upload tools
      continue-on-error: true
      uses: softprops/action-gh-release@v2
      with:
        tag_name: tools
        name: tools
        files: tools*.zip
