
name: cache-toolchain

on:
  #schedule:
  #  - cron: '10 0 * * MON'
    
  workflow_dispatch:
    inputs:
      toolchain:
        description: "toolchain"
        required: false
        default: "x86_64"
        type: choice
        options:
        - x86_64
        - arm64

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Cache toolchain-x86_64
      if: ${{ inputs.toolchain == 'x86_64' }}
      uses: actions/cache@main
      id: toolchain-x86_64
      with:
        path: ${{ github.workspace }}/tools
        key: toolchain-x86_64
    - name: Cache toolchain-arm64
      if: ${{ inputs.toolchain == 'arm64' }}
      uses: actions/cache@main
      id: toolchain-arm64
      with:
        path: ${{ github.workspace }}/tools
        key: toolchain-arm64
    - name: Setup toolchain-x86_64
      if: ${{ inputs.toolchain == 'x86_64' && steps.toolchain-x86_64.outputs.cache-hit != 'true' }} 
      run: |
        curl -OL https://github.com/${{ github.repository }}/releases/download/toolchain/toolchain-x86_64-latest.zip
        unzip toolchain-x86_64-latest.zip
        mv workspace tools
    - name: Setup toolchain-arm64
      if: ${{ inputs.toolchain == 'arm64' && steps.toolchain-arm64.outputs.cache-hit != 'true' }} 
      run: |
        curl -OL https://github.com/${{ github.repository }}/releases/download/toolchain/toolchain-arm64-latest.zip
        unzip toolchain-arm64-latest.zip


