name: libiconv
on:
  #schedule:
  #  - cron: '10 0 * * MON'
    
  workflow_dispatch:
    inputs:   
      arch:
        description: "Build target"
        required: false
        default: "x86_64"
        type: choice
        options:
        - x86_64
        - arm64
      os:
        description: "Only macos-14 support arm64"
        required: false
        default: "macos-13"
        type: choice
        options:
        - macos-13
        - macos-14

jobs:
  libiconv:
    runs-on: ${{ inputs.os }}
    env:
      ARCHS: ${{ inputs.arch }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:   
    - name: Checkout
      uses: actions/checkout@main
    - name: Loading toolchain-${{ inputs.arch }} cache
      uses: actions/cache@main
      with:
        path: ${{ github.workspace }}/workspace
        key: toolchain-${{ inputs.arch }}
    - name: Switch to Xcode 15.2
      run: |
        sudo xcode-select --reset
        sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer  
    - name: Build
      run: |
        chmod +x ./scripts/libiconv.sh
        ./scripts/libiconv.sh
    - name: Delete
      uses: mknejp/delete-release-assets@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: dev-${{ inputs.arch }}
        assets: libiconv*.xz
        fail-if-no-assets: false
        fail-if-no-release: false
    - name: Upload
      continue-on-error: true
      uses: softprops/action-gh-release@master
      with:
        tag_name: dev-${{ inputs.arch }}
        name: dev-${{ inputs.arch }}
        files: libiconv.tar.xz
