name: Add New Branch

on: 
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Install git
      run: |
        sudo apt-get update
        sudo apt-get -y install git
    - name: Set env
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - name: Executable flag setting
      run: |
        git checkout --orphan new_branch
        git add -A
        git commit -m "Initial commit"
        git push --set-upstream origin new_branch